# Use the official Nginx image from Docker Hub
FROM nginx:latest

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy the custom configuration file from the current directory
COPY default.conf /etc/nginx/conf.d/

# Optionally, copy your static HTML files to the image
COPY html /usr/share/nginx/html

# Expose port 80 and 443 (if you are planning to use HTTPS)
EXPOSE 80 

# Command to run when the container starts
CMD ["nginx", "-g", "daemon off;"]