"""empty message

Revision ID: 3f258907f6e5
Revises: e82877344456
Create Date: 2026-04-24 23:03:19.373717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f258907f6e5'
down_revision: Union[str, Sequence[str], None] = 'e82877344456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('parent_ts', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('userinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('salted_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userinfo_id'), 'userinfo', ['id'], unique=False)
    op.create_index(op.f('ix_userinfo_name'), 'userinfo', ['name'], unique=True)
    op.create_table('conv_privacy_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conv_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['conv_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conv_id', 'user_id', name='conv_user_uc')
    )
    op.create_index(op.f('ix_conv_privacy_members_id'), 'conv_privacy_members', ['id'], unique=False)
    op.create_table('conv_starting_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('parent_ts', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conv_starting_points_id'), 'conv_starting_points', ['id'], unique=False)
    op.create_table('convomessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convomessage_id'), 'convomessage', ['id'], unique=False)
    op.create_table('convchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.Float(), nullable=True),
    sa.Column('conv_id', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(), nullable=True),
    sa.Column('change_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['convomessage.id'], ),
    sa.ForeignKeyConstraint(['conv_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convchanges_id'), 'convchanges', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_convchanges_id'), table_name='convchanges')
    op.drop_table('convchanges')
    op.drop_index(op.f('ix_convomessage_id'), table_name='convomessage')
    op.drop_table('convomessage')
    op.drop_index(op.f('ix_conv_starting_points_id'), table_name='conv_starting_points')
    op.drop_table('conv_starting_points')
    op.drop_index(op.f('ix_conv_privacy_members_id'), table_name='conv_privacy_members')
    op.drop_table('conv_privacy_members')
    op.drop_index(op.f('ix_userinfo_name'), table_name='userinfo')
    op.drop_index(op.f('ix_userinfo_id'), table_name='userinfo')
    op.drop_table('userinfo')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
